functionsDirectory = "/Users/erik/Sites/habitualos/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/erik/Sites/habitualos/_site"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/erik/Sites/habitualos/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/do/action/*"
to = "/do/action/"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/do/file/*"
to = "/do/file/"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]